api_platform:
  title: GBSW Dragon Treasure API.
  version: 1.0.0
  formats:
    jsonld: [ 'application/ld+json' ]
    html: [ 'text/html' ]
    json: [ 'application/json' ]
  docs_formats:
    jsonld: [ 'application/ld+json' ]
    jsonopenapi: [ 'application/vnd.openapi+json' ]
    html: [ 'text/html' ]
    json: [ 'application/json' ]
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  graphql:
    graphiql:
      enabled: true
  keep_legacy_inflector: false
  use_symfony_listeners: true

when@prod:
  api_platform:
    enable_entrypoint: false
    enable_swagger: false
    enable_swagger_ui: false