<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNiBf3O6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNiBf3O6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNiBf3O6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNiBf3O6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNiBf3O6\App_KernelDevDebugContainer([
    'container.build_hash' => 'NiBf3O6',
    'container.build_id' => 'adf2fb14',
    'container.build_time' => 1718466587,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNiBf3O6');
